### ISSUE TITLE
github link broken on github.io page

### ISSUE THREAD

**Issue by lukasheinrich** [CERNStudyGroup/cernstudygroup.github.io#15] opened 2016-02-13 18:20 UTC
tried to find the place in source, but failed. The link here

WANT TO BE NOTIFIED OF OUR UPCOMING EVENTS?
Head over to GitHub and watch our repository, like this:

the link pointing to GH is broken.

**Comment by adavidzh** [comment] 2016-02-14 10:43
Duplicate of #7

**Closed as completed by adavidzh** 2016-02-14 10:43 UTC
